const {test}=require('node:test');
const assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {loadExtension,baseVscode,uri}=require('./helpers');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));

test('host validates sentences against official text and invalidates pending audio on pause, mode change and new tests',async()=>{
  let browser,receive,dispose,panel;
  class FakeBrowser extends EventEmitter {
    constructor(){super();browser=this;this.closed=false;this.round=0;this.state={ready:true,target:'Hello',wordIndex:0,typed:'',speechEnd:4,testId:'first',speechWords:['Hello','world.','Next','sentence.'].map((text,index)=>({text,index}))};}
    async launch(){} async attach(){return this.state;} async waitForTest(){return this.state;}
    async snapshot(){return this.state;} async release(){} async close(){this.closed=true;}
    async nextTest(){this.round++;return this.state;}
  }
  const vscode=baseVscode(),commands={},messages=[],pending=[];
  const document={fileName:'private.js',languageId:'javascript',uri:uri('private.js'),getText:()=> 'const neverSendThisCode = 1;'};
  vscode.StatusBarAlignment={Right:1,Left:0};vscode.ViewColumn={One:1};
  vscode.commands={registerCommand:(name,fn)=>{commands[name]=fn;return {dispose(){}};}};
  vscode.window={activeTextEditor:{document,viewColumn:1},createStatusBarItem:()=>({show(){},hide(){},dispose(){}}),
    showErrorMessage:text=>assert.fail(text),showTextDocument:async()=>{},
    createWebviewPanel:()=>panel={active:true,webview:{cspSource:'test:',asWebviewUri:x=>x.toString(),postMessage:m=>messages.push(m),onDidReceiveMessage:fn=>receive=fn},onDidChangeViewState(){},onDidDispose:fn=>dispose=fn,dispose:()=>dispose()}};
  let changeConfig;
  vscode.workspace.onDidChangeConfiguration=fn=>{changeConfig=fn;return {dispose(){}};};
  const speechConfig={ttsEndpoint:'http://localhost/tts'};
  vscode.workspace.getConfiguration=()=>({get:key=>speechConfig[key]});
  const stored=new Map([['practicePreferences',{speechMode:'sentence',speechEnabled:true}]]);
  const prepared=[];
  // Keep playback requests controllable here; the real scheduler is tested in tts.test.js.
  const extension=loadExtension(vscode,{BrowserBridge:FakeBrowser,findBrowser:()=> 'fake'}, {'./speech/tts':{createSpeechCache:()=>({
    prepare:(endpoint,texts,options)=>prepared.push({endpoint,texts,options}),
    get:(endpoint,text,options,signal)=>new Promise(resolve=>pending.push({text,options,signal,resolve})),
    clear(){},cancelPending(){}
  })}});
  extension.activate({subscriptions:[],extensionUri:uri(process.cwd()),globalStorageUri:uri('.test-output/speech-host'),globalState:{get:key=>stored.get(key),update:async(key,value)=>stored.set(key,value)}});
  try {
    await commands['codeType.start']();
    const session=panel.webview.html.match(/data-session="([^"]+)"/)[1];
    const emit=data=>receive({session,...data});
    const latest=()=>messages.filter(m=>m.type==='state').at(-1);
    const arm=async()=>{emit({type:'arm'});await delay(15);};
    const request=id=>emit({type:'speech',id,epoch:latest().speechEpoch,text:latest().sentence.text});
    emit({type:'ready'});await arm();
    assert.equal(latest().sentence.text,'Hello world.');
    assert.deepEqual(prepared.at(-1).texts,['Hello world.','Next sentence.'],'official sentences are prepared before any speech request');
    assert.equal(stored.get('practicePreferences').smartSpeech,false,'smart speech defaults off');
    const preparationCount=prepared.length;
    browser.state={...browser.state,typed:'H'};await arm();
    browser.state={...browser.state,typed:'He'};await arm();
    assert.equal(prepared.length,preparationCount,'typing within the same word does not rebuild full-round lookahead');
    emit({type:'speech',id:0,epoch:latest().speechEpoch,text:document.getText()});
    assert.equal(pending.length,0,'arbitrary text and source code cannot reach TTS');
    request(1);
    browser.state={...browser.state,wordIndex:1,target:'world.'};
    await arm();
    assert.equal(pending[0].signal.aborted,false,'within-sentence state updates leave synthesis running');
    browser.state={...browser.state,wordIndex:2,target:'Next'};
    await arm();
    assert.equal(pending[0].signal.aborted,false,'FIFO sentence synthesis survives typing transitions');
    emit({type:'speech-cancel'});
    pending[0].resolve({mime:'audio/wav',audio:'old'});await delay(0);
    assert.equal(messages.filter(m=>m.type==='speech').length,0);
    request(2);emit({type:'pause'});await delay(0);
    assert.equal(pending[1].signal.aborted,true);
    pending[1].resolve({mime:'audio/wav',audio:'old'});await delay(0);
    assert.equal(messages.filter(m=>m.type==='speech').length,0);
    await arm();request(3);
    const oldEpoch=latest().speechEpoch;
    browser.state={...browser.state,wordIndex:0,target:'Hello',testId:'repeat-same-text'};
    await arm();
    assert.ok(latest().speechEpoch>oldEpoch,'same-text website restart has a new generation');
    assert.equal(pending[2].signal.aborted,true);
    emit({type:'speech',id:4,epoch:oldEpoch,text:'Hello world.'});
    assert.equal(pending.length,3,'old Webview request rejected after restart');
    request(5);
    emit({type:'preferences',displayMode:'dock',speechEnabled:true,speechMode:'word'});
    await delay(0);
    assert.deepEqual(prepared.at(-1).texts,['Hello','world','Next','sentence'],'word lookahead uses the same punctuation filtering as playback');
    assert.equal(pending[3].signal.aborted,true,'mode switch cancels pending sentence');
    emit({type:'speech',id:6,epoch:latest().speechEpoch,text:'Hello'});
    assert.equal(pending.at(-1).text,'Hello','word mode still validates only the official target');
    emit({type:'preferences',displayMode:'dock',speechEnabled:false,speechMode:'sentence'});
    assert.equal(pending.at(-1).signal.aborted,true);
    assert.equal(stored.get('practicePreferences').speechMode,'sentence');
    emit({type:'preferences',displayMode:'dock',speechEnabled:true,speechMode:'sentence'});
    request(7);emit({type:'next-test'});await delay(30);
    assert.equal(pending.at(-1).signal.aborted,true,'Next cancels pending audio');
    request(8);emit({type:'repeat-test'});await delay(30);
    assert.equal(pending.at(-1).signal.aborted,true,'Repeat cancels pending audio');
    browser.state={...browser.state,testMode:'words'};
    await arm();
    const beforeWords=pending.length;
    request(9);
    assert.equal(pending.length,beforeWords,'words mode rejects a sentence even when sentence preference is saved');
    emit({type:'speech',id:10,epoch:latest().speechEpoch,text:'Hello',unit:'word'});
    assert.equal(pending.at(-1).text,'Hello');
    browser.state={...browser.state,wordIndex:1,target:'world.'};
    await arm();
    assert.equal(pending.at(-1).signal.aborted,false,'word transition leaves playback cancellation to the Webview');
    emit({type:'preferences',displayMode:'dock',speechEnabled:true,speechMode:'hybrid',smartSpeech:true});
    assert.equal(stored.get('practicePreferences').smartSpeech,true,'smart speech is saved independently');
    browser.state={...browser.state,testMode:'quote',wordIndex:0,target:'Hello'};
    await arm();
    browser.state={...browser.state,wordIndex:1,target:'world.'};
    await arm();
    emit({type:'speech',id:11,epoch:latest().speechEpoch,text:'Hello world.',unit:'sentence',sentenceId:'0:2'});
    assert.equal(pending.at(-1).signal.aborted,false,'hybrid sentence is not interrupted by word changes');
    browser.state={...browser.state,wordIndex:2,target:'Next'};
    await arm();
    assert.equal(pending.at(-1).signal.aborted,false,'typing into the next sentence must not cancel hybrid synthesis');
    const beforeLate=pending.length;
    emit({type:'speech',id:111,epoch:latest().speechEpoch,text:'Hello world.',unit:'sentence',sentenceId:'0:2'});
    assert.equal(pending.length,beforeLate+1,'a delayed request still matches the official sentence from this round');
    emit({type:'speech',id:112,epoch:latest().speechEpoch,text:'invented text',unit:'sentence',sentenceId:'0:2'});
    assert.equal(pending.length,beforeLate+1,'sentence identity cannot authorize arbitrary text');
    browser.state={...browser.state,wordIndex:1,target:'world.'};
    await arm();
    assert.equal(pending.at(-1).signal.aborted,false,'backtracking must not cancel the protected hybrid sentence');
    emit({type:'speech',id:12,epoch:latest().speechEpoch,text:'world.',unit:'word'});
    assert.equal(pending.at(-1).text,'world');
    const beforeStale=pending.length;
    emit({type:'speech',id:13,epoch:latest().speechEpoch,text:'Hello',unit:'word'});
    assert.equal(pending.length,beforeStale,'requests without an index still match the current word');
    browser.state={...browser.state,wordIndex:2,target:'Next'};
    await arm();
    assert.equal(pending.at(-1).signal.aborted,false,'hybrid word playback survives word transitions');
    assert.equal(stored.get('practicePreferences').speechMode,'hybrid');
    const beforeEarly=pending.length;
    emit({type:'speech',id:14,epoch:latest().speechEpoch,text:'sentence.',wordIndex:3,unit:'word'});
    assert.equal(pending.length,beforeEarly,'incomplete current word cannot authorize early speech');
    browser.state={...browser.state,typed:'Next'};await arm();
    emit({type:'speech',id:15,epoch:latest().speechEpoch,text:'sentence.',wordIndex:3,unit:'word'});
    assert.equal(pending.at(-1).text,'sentence','correct completion allows the next official word before space');
    emit({type:'speech',id:16,epoch:latest().speechEpoch,text:'invented',wordIndex:3,unit:'word'});
    assert.equal(pending.length,beforeEarly+1,'early speech still validates official text');
    browser.state={...browser.state,typed:'Nexx'};await arm();
    emit({type:'speech',id:17,epoch:latest().speechEpoch,text:'sentence.',wordIndex:3,unit:'word'});
    assert.equal(pending.length,beforeEarly+2,'previously authorized queued word survives a later correction');
    browser.state={...browser.state,testId:'boundary-case',wordIndex:1,target:'world.',typed:'world'};await arm();
    const beforeBoundary=pending.length;
    emit({type:'speech',id:171,epoch:latest().speechEpoch,text:'Next sentence.',sentenceId:'2:4',unit:'sentence'});
    assert.equal(pending.length,beforeBoundary,'next sentence requires the entire boundary token including punctuation');
    browser.state={...browser.state,typed:'world.'};await arm();
    assert.equal(latest().nextSentence.text,'Next sentence.');
    emit({type:'speech',id:172,epoch:latest().speechEpoch,text:'Next',wordIndex:2,unit:'word'});
    assert.equal(pending.length,beforeBoundary,'hybrid lookahead cannot read the next sentence first word alone');
    emit({type:'speech',id:173,epoch:latest().speechEpoch,text:'Next sentence.',sentenceId:'2:4',unit:'sentence'});
    assert.equal(pending.at(-1).text,'Next sentence.','boundary completion authorizes the entire next official sentence');
    emit({type:'speech',id:174,epoch:latest().speechEpoch,text:'invented sentence.',sentenceId:'2:4',unit:'sentence'});
    assert.equal(pending.length,beforeBoundary+1);
    emit({type:'speech-cancel'});
    browser.state={...browser.state,target:'.',wordIndex:0,typed:'',speechWords:[{index:0,text:'.'}],speechEnd:1};await arm();
    const beforePunctuation=pending.length;
    emit({type:'speech',id:18,epoch:latest().speechEpoch,text:'.',wordIndex:0,unit:'word'});
    assert.equal(pending.length,beforePunctuation,'standalone punctuation never reaches TTS');
    assert.ok(messages.some(message=>message.type==='speech-ended' && message.id===18),'silent token completes without blocking playback');
    for(const request of pending)request.resolve({mime:'audio/wav',audio:'late'});
    await delay(0);
    assert.equal(messages.filter(m=>m.type==='speech').length,0,'no canceled response reaches playback');
    browser.state={...browser.state,target:'a',wordIndex:0,typed:'',speechWords:['a','man;','girl,','and','a','ship'].map((text,index)=>({text,index})),speechEnd:6};await arm();
    assert.ok(prepared.at(-1).texts.includes('girl'),'the word itself is still prepared');
    assert.ok(!prepared.at(-1).texts.includes('girl,'),'single-word sentence audio is not synthesized redundantly');
    assert.equal(latest().sentence.wordCount,2);
    assert.equal(latest().nextSentence.wordCount,1);
    const longText=Array.from({length:60},(_,index)=>[`Part${index}`,'ends.']).flat();
    browser.state={...browser.state,target:longText[0],speechWords:longText.map((text,index)=>({text,index})),speechEnd:longText.length};await arm();
    assert.ok(prepared.at(-1).texts.includes('Part2 ends.'),'nearby sentences are still prepared');
    assert.ok(prepared.at(-1).texts.includes('Part59 ends.'),'all available sentence audio is scheduled in the background');
    assert.ok(prepared.at(-1).texts.includes('Part16'),'hybrid mode prepares individual words 32 positions ahead');
    assert.ok(!prepared.at(-1).texts.includes('Part17'),'individual word preparation stays within its bounded window');
    assert.ok(prepared.at(-1).texts.indexOf('Part2 ends.')<prepared.at(-1).texts.indexOf('Part3'),'nearby sentences keep priority over the extended word window');
    emit({type:'preferences',displayMode:'dock',speechEnabled:true,speechMode:'word'});await delay(10);
    assert.ok(prepared.at(-1).texts.includes('Part16'),'word mode uses the enlarged window too');
    assert.ok(!prepared.at(-1).texts.includes('Part17'));
    assert.ok(!prepared.at(-1).texts.includes('Part0 ends.'),'word mode does not synthesize sentences');
    emit({type:'preferences',displayMode:'dock',speechEnabled:true,speechMode:'hybrid'});await delay(10);
    browser.state={...browser.state,target:longText[118],wordIndex:118};await arm();
    assert.ok(prepared.at(-1).texts.includes('Part59 ends.'),'lookahead advances with the typing position');
    assert.ok(prepared.at(-1).texts.includes('Part0 ends.'),'round audio stays available for delayed FIFO playback');
    emit({type:'speech',id:180,epoch:latest().speechEpoch,text:longText[0],wordIndex:0,unit:'word'});
    assert.equal(pending.at(-1).text,longText[0],'FIFO can play official earlier words after typing advances');
    emit({type:'speech-cancel'});
    const reads=[];
    browser.speechSnapshot=()=>new Promise(resolve=>reads.push(resolve));
    browser.sendKey=async()=>{browser.state={...browser.state,typed:'P'};return browser.state;};
    browser.state={...browser.state,testId:'async-round',speechRevision:'async-round:120',wordIndex:0,target:longText[0],typed:'',speechWords:longText.slice(0,97).map((text,index)=>({text,index}))};
    await arm();
    assert.equal(reads.length,1);
    emit({type:'key',sentAt:Date.now(),event:{type:'keydown',key:'P',code:'KeyP',keyCode:80,modifiers:8}});
    await delay(10);
    assert.equal(latest().typed,'P','input is processed while full-round text and audio requests are pending');
    assert.equal(reads.length,1,'ordinary input never starts a second full-round scan');
    reads[0]({...browser.state,typed:'',speechWords:longText.map((text,index)=>({text,index}))});
    await delay(10);
    assert.equal(latest().typed,'P','background text cannot restore stale typing');
    assert.ok(prepared.at(-1).texts.includes('Part59 ends.'));
    assert.equal(latest().speechWords,undefined,'the full round is not retransmitted to the rendering page');
    browser.state={...browser.state,speechRevision:'async-round:121'};await arm();
    assert.equal(reads.length,2);
    const stale={...browser.state,speechWords:longText.map((text,index)=>({text,index}))};
    browser.state={...browser.state,testId:'fresh-round',speechRevision:'fresh-round:2',target:'Fresh',speechEnd:2,speechWords:[{index:0,text:'Fresh'},{index:1,text:'round.'}]};await arm();
    reads[1](stale);await delay(10);
    assert.equal(latest().sentence.text,'Fresh round.','late full-round text is rejected after restart');
    assert.equal(reads.length,3,'new round receives its own background scan');
    reads[2](browser.state);await delay(10);
    Object.assign(speechConfig,{ttsProvider:'gpt-sovits',ttsReferenceAudio:' D:/Models/reference.wav ',ttsReferenceText:' The reference. ',ttsReferenceLanguage:'en'});
    await arm();
    const expectedOptions={voice:'',rate:1,provider:'gpt-sovits',referenceAudio:'D:/Models/reference.wav',referenceText:'The reference.',referenceLanguage:'en'};
    assert.deepEqual(prepared.at(-1).options,expectedOptions,'background preparation receives the fixed reference settings');
    emit({type:'speech',id:181,epoch:latest().speechEpoch,text:'Fresh round.',sentenceId:'0:2',unit:'sentence'});
    assert.deepEqual(pending.at(-1).options,expectedOptions,'foreground playback uses the same provider and reference');
    const previous=pending.at(-1),referenceEpoch=latest().speechEpoch;
    speechConfig.ttsReference={audio:'D:/Models/second.wav',text:'Second reference.',language:'en'};
    changeConfig({affectsConfiguration:key=>key==='codeType.ttsReference'});
    await delay(10);
    assert.equal(previous.signal.aborted,true,'changing reference rejects old in-flight audio');
    assert.ok(latest().speechEpoch>referenceEpoch,'changing reference resets Webview playback and highlighting');
    assert.equal(prepared.at(-1).options.referenceAudio,'D:/Models/second.wav');
    assert.equal(prepared.at(-1).options.referenceText,'Second reference.');
    emit({type:'speech-cancel'});
    pending.at(-1).resolve({mime:'audio/wav',audio:'late'});
  } finally {await extension.deactivate();}
});
