const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { loadExtension, baseVscode, uri } = require('./helpers');

async function main() {
  // Set PLAYWRIGHT_MODULE only when using a preinstalled runtime instead of a local package.
  const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
  const vscode = baseVscode();
  const { htmlFor } = loadExtension(vscode);
  let origin;
  const server = http.createServer((req, res) => {
    if (req.url === '/') {
      let html = htmlFor({ cspSource: origin, asWebviewUri: value => `${origin}/media/${path.basename(value.fsPath)}` }, uri(path.resolve(__dirname, '..')), 'ui-test', { fileName: 'session.ts', languageId: 'typescript', uri: uri('session.ts') });
      const nonce = html.match(/script-src 'nonce-([^']+)'/)[1];
      // Reproduce the host Webview's default code background, absent in an ordinary browser.
      html = html.replace('</head>', `<style nonce="${nonce}">code{background-color:var(--vscode-textCodeBlock-background,#292929)}</style></head>`);
      html = html.replace('<body class="reading-strip"', '<body class="reading-strip vscode-dark"').replace('</head>', `<style nonce="${nonce}">body{--vscode-editor-background:#1e1e1e;--vscode-editor-foreground:#d4d4d4;--vscode-font-family:Segoe UI,sans-serif;--vscode-editorLineNumber-foreground:#858585;--vscode-editorGhostText-foreground:#777}</style><script nonce="${nonce}">window.messages=[];window.acquireVsCodeApi=()=>({postMessage:m=>window.messages.push(m)});</script></head>`);
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(html);
    } else if (['/media/practice.js', '/media/word-feedback.js', '/media/practice.css'].includes(req.url)) {
      res.writeHead(200, { 'Content-Type': req.url.endsWith('.js') ? 'text/javascript' : 'text/css' });
      res.end(fs.readFileSync(path.join(__dirname, '..', req.url)));
    } else { res.writeHead(404); res.end(); }
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  origin = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1200, height: 720 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(origin);
    await page.waitForFunction(() => window.messages.some(m => m.type === 'ready'));
    await page.evaluate(()=>window.postMessage({type:'preferences',displayMode:'comment',speechEnabled:false}));
    assert.equal(await page.locator('#next-test').isVisible(),false,'test controls are collapsed by default');
    const menuClick = async selector => {
      await page.locator('#tools-menu summary').click();
      await page.locator(selector).click();
    };
    await page.locator('#resume').click();
    await page.evaluate(() => window.postMessage({ type: 'armed' }));
    await page.waitForFunction(() => document.body.classList.contains('armed'));
    for (const indent of ['    ','\t']) {
      const html=`for app in apps:\n${indent}for entry in entries:\n${indent.repeat(2)}<span id="nested-if">if</span> not entry.id:\n${indent.repeat(3)}`;
      await page.evaluate(html=>window.postMessage({type:'code',html,lines:4,tabSize:4,reveal:true}),html);
      await page.waitForFunction(()=>!!document.getElementById('nested-if'));
      const before=await page.locator('#caret').boundingBox();
      const parent=await page.locator('#nested-if').boundingBox();
      assert.ok(before.x>parent.x+20,'nested body is indented a full level after if');
      await page.evaluate(html=>window.postMessage({type:'code',html:html+'<span id="nested-body">c</span>',lines:4,tabSize:4}),html);
      await page.waitForFunction(()=>!!document.getElementById('nested-body'));
      const body=await page.locator('#nested-body').boundingBox();
      assert.ok(Math.abs(before.x-body.x)<1,'blank-line caret exactly matches the first body character');
    }
    await page.keyboard.press('a');
    await page.keyboard.press('Backspace');
    const keys = await page.evaluate(() => window.messages.filter(m => m.type === 'key').map(m => [m.event.type, m.event.key]));
    assert.deepEqual(keys, [['keydown','a'], ['keyup','a'], ['keydown','Backspace'], ['keyup','Backspace']]);
    await page.evaluate(() => {
      window.postMessage({ type: 'code', html: '<span class="hljs-keyword">export</span> <span class="hljs-keyword">async function</span> <span class="hljs-title">loadSession</span>(id: <span class="hljs-built_in">string</span>) {\n  <span class="hljs-keyword">const</span> session = <span class="hljs-keyword">await</span> store.get(id);\n  <span class="hljs-keyword">if</span> (!session) {\n    <span class="hljs-keyword">return</span> <span class="hljs-literal">null</span>;\n  }\n\n  <span class="hljs-keyword">return</span> sess', lines: 7 });
    });
    const vocabulary = 'world through people make time work point system first because change before another between under place again right never small new find early while';
    const preview = Array.from({length:72},(_,index)=>({index,text:vocabulary.split(' ')[index%24]}));
    const state = async (wordIndex, typed='') => {
      await page.evaluate(data=>window.postMessage({type:'state',ready:true,...data}), {wordIndex,typed,target:preview[wordIndex].text,preview});
      await page.waitForFunction(({wordIndex,typed})=>document.querySelector('.prompt-word.current')?.dataset.index===String(wordIndex) && document.getElementById('input-echo').textContent===(typed||'…'), {wordIndex,typed});
    };
    await state(0,'wo');
    assert.equal(await page.locator('#code').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)','host inline-code background must not create grey strips');
    assert.equal(await page.locator('.prompt-word').count(),24);
    const positions = () => page.locator('.prompt-word').evaluateAll(words=>words.map(word=>{const r=word.getBoundingClientRect();return [r.x,r.y,r.width]}));
    const initialPositions=await positions();
    await state(0,'woxxxxxxxxxxxx');
    assert.deepEqual(await positions(),initialPositions,'extra mistakes must not shift the words');
    assert.equal(await page.locator('.prompt-word.current').textContent(),'world');
    await state(1,'t');
    assert.deepEqual(await positions(),initialPositions,'advancing a word must not replace or move the reading group');
    const promptBox=await page.locator('#prompt-panel').boundingBox();
    await page.evaluate(()=>window.postMessage({type:'code',html:'const value = 1;\n'.repeat(100),lines:101}));
    await page.waitForFunction(()=>document.getElementById('editor').scrollTop>0);
    assert.deepEqual(await page.locator('#prompt-panel').boundingBox(),promptBox,'code scrolling must not move input');
    const scrollTop=await page.locator('#editor').evaluate(el=>el.scrollTop);
    await page.evaluate(()=>window.postMessage({type:'code',html:'const value = 1;\n'.repeat(101),lines:102}));
    await page.waitForFunction(()=>document.getElementById('gutter').textContent.endsWith('102'));
    assert.equal(await page.locator('#editor').evaluate(el=>el.scrollTop),scrollTop,'a single code line should not scroll when caret has room: '+JSON.stringify(await page.evaluate(()=>({editor:document.getElementById('editor').getBoundingClientRect().toJSON(),caret:document.getElementById('caret').getBoundingClientRect().toJSON(),scrollHeight:document.getElementById('editor').scrollHeight}))));
    await state(24);
    assert.equal(await page.locator('.prompt-word').first().getAttribute('data-index'),'24');
    await state(23);
    assert.equal(await page.locator('.prompt-word').first().getAttribute('data-index'),'0','backspace across group boundary restores previous words');
    await state(1,'th');
    fs.mkdirSync('.test-output', { recursive: true });
    await page.setViewportSize({width:560,height:720});
    await page.waitForFunction(()=>document.querySelectorAll('.prompt-word').length===24);
    await page.screenshot({path:'.test-output/practice-narrow.png'});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.setViewportSize({width:430,height:720});
    await page.waitForFunction(()=>document.querySelectorAll('.prompt-word').length===12);
    await state(11);
    const activeBox=await page.locator('.prompt-word.current').boundingBox();
    const wordBox=await page.locator('#word-window').boundingBox();
    assert.ok(activeBox.y>=wordBox.y && activeBox.y+activeBox.height<=wordBox.y+wordBox.height+1,'current word stays visible in a narrow editor');
    await page.setViewportSize({width:1200,height:720});
    await state(0,'wo');
    await page.evaluate(()=>window.postMessage({type:'code',html:'<span class="hljs-keyword">export async function</span> <span class="hljs-title">loadSession</span>(id: <span class="hljs-built_in">string</span>) {\n  <span class="hljs-keyword">const</span> session = <span class="hljs-keyword">await</span> store.get(id);\n  <span class="hljs-keyword">if</span> (!session) {\n    <span class="hljs-keyword">return</span> <span class="hljs-literal">null</span>;\n  }\n\n  <span class="hljs-keyword">return</span> sess',lines:7,reveal:true}));
    await page.evaluate(()=>window.postMessage({type:'suggestions',items:[{label:'session',detail:'const session: Session',origin:'VS Code'},{label:'sessionStore',detail:'当前文件',origin:'file'}]}));
    await page.waitForFunction(()=>!document.getElementById('suggestions').hidden);
    await page.screenshot({ path: '.test-output/practice-dark.png' });
    await menuClick('#settings-toggle');
    await page.locator('#display-mode').selectOption('statusbar');
    await page.locator('#statusbar-words').selectOption('16');
    assert.ok(await page.evaluate(()=>window.messages.some(m=>m.type==='preferences' && m.statusbarWords===16)));
    assert.equal(await page.locator('#prompt-panel').isVisible(),false);
    assert.ok(await page.evaluate(()=>window.messages.some(m=>m.type==='preferences' && m.displayMode==='statusbar')));
    await page.screenshot({path:'.test-output/practice-statusbar.png'});
    await page.locator('#display-mode').selectOption('inline');
    await page.locator('#inline-words').selectOption('8');
    assert.ok(await page.evaluate(()=>window.messages.some(m=>m.type==='preferences' && m.inlineWords===8 && m.statusbarWords===16)));
    assert.equal(await page.locator('#inline-hint .inline-word').count(),8);
    assert.equal(await page.locator('#inline-hint .current .correct').count(),2,'inline preview preserves per-character feedback');
    assert.equal(await page.locator('#prompt-panel').isVisible(),false);
    assert.equal(await page.locator('#inline-hint').isVisible(),true);
    assert.ok((await page.locator('#inline-hint').textContent()).includes('// world'));
    await menuClick('#settings-toggle');
    await page.screenshot({path:'.test-output/practice-inline.png'});
    await page.setViewportSize({width:430,height:720});
    await page.waitForFunction(()=>{const rect=document.getElementById('inline-hint').getBoundingClientRect();return rect.x>=0 && rect.right<=innerWidth});
    const hintBox=await page.locator('#inline-hint').boundingBox();
    assert.ok(hintBox.x>=0 && hintBox.x+hintBox.width<=430,'inline hint stays within narrow editor');
    await page.setViewportSize({width:1200,height:720});
    await menuClick('#settings-toggle');
    await page.locator('#display-mode').selectOption('reading');
    assert.equal(await page.locator('#prompt-panel').isVisible(),true);
    await menuClick('#speech-toggle');
    assert.equal(await page.locator('#settings-panel').isVisible(),false,'speech configuration is independent of test settings');
    await page.locator('#speech-configure').click();
    assert.ok(await page.evaluate(()=>window.messages.some(m=>m.type==='speech-settings')));
    await page.locator('#speech-enabled').check();
    await page.evaluate(()=>window.postMessage({type:'armed'}));
    await page.waitForFunction(()=>document.body.classList.contains('armed'));
    await state(0,'wo');
    await page.locator('#speech-enabled').uncheck();
    await page.locator('#speech-mode').selectOption('word');
    await state(2);
    await menuClick('#settings-toggle');
    await page.locator('#display-mode').selectOption('comment');
    await menuClick('#settings-toggle');
    await menuClick('#settings-toggle');
    await page.locator('#display-mode').selectOption('dock');
    await page.locator('#dock-style').selectOption('standard');
    await page.locator('#show-progress').check();
    await page.locator('#dock-font').fill('18');
    await page.locator('#dock-font').dispatchEvent('change');
    await page.locator('#dock-lines').check();
    assert.ok(await page.evaluate(()=>window.messages.some(m=>m.type==='preferences' && m.displayMode==='dock' && m.dockFont===18 && m.dockLines===2)));
    await menuClick('#settings-toggle');
    const punctuated = ('"Hello," she said. (Really?) Yes! Wait... it\'s 3.14; [ready] {set} go: now? Almost, keep typing! Clear words stay still through every single key. '.repeat(2).trim()).split(' ').map((text,index)=>({text,index}));
    const dockState=async(index,typed)=>{
      await page.evaluate(data=>window.postMessage({type:'state',ready:true,...data}),{wordIndex:index,target:punctuated[index].text,typed,preview:punctuated});
      await page.waitForFunction(({index,typed})=>document.querySelector('.prompt-word.current')?.dataset.index===String(index) && document.getElementById('input-echo').textContent===(typed||'…'),{index,typed});
    };
    await dockState(0,'"He');
    const dockPositions=await positions();
    const dockPanel=await page.locator('#prompt-panel').boundingBox();
    const progressBox=await page.locator('#dock-progress').boundingBox();
    const editorBox=await page.locator('#editor').boundingBox();
    assert.ok(Math.abs(editorBox.y+editorBox.height-dockPanel.y)<1,'editor reserves room above the reading strip');
    assert.ok(Math.abs(dockPanel.y+dockPanel.height-692)<1,'reading strip is anchored above the footer');
    await dockState(0,'"Hexxxxxxxxxxxxxx');
    assert.deepEqual(await positions(),dockPositions,'punctuation and extra mistakes cannot move the text');
    assert.equal(await page.locator('#word-list .incorrect').count(),5);
    assert.deepEqual(await page.locator('#dock-progress').boundingBox(),progressBox,'counter has a fixed footprint');
    await dockState(1,'s');
    assert.deepEqual(await positions(),dockPositions,'word changes only move highlight');
    assert.equal(await page.locator('#word-list [data-index="0"] .incorrect').count(),5,'previous errors survive changing words');
    assert.ok(await page.locator('#word-list [data-index="0"]').evaluate(el=>el.classList.contains('extra-error')));
    await page.evaluate(()=>window.postMessage({type:'code',html:'const row = 1;\n'.repeat(90),lines:91,reveal:true}));
    await page.waitForFunction(()=>document.getElementById('gutter').textContent.endsWith('91'));
    assert.deepEqual(await page.locator('#prompt-panel').boundingBox(),dockPanel,'code scroll cannot move reading strip');
    await page.screenshot({path:'.test-output/practice-dock-dark.png'});
    await page.setViewportSize({width:430,height:720});
    await page.waitForFunction(()=>document.getElementById('prompt-panel').getBoundingClientRect().width===414);
    await dockState(9,'{s');
    const dockCurrent=await page.locator('.prompt-word.current').boundingBox();
    const dockWindow=await page.locator('#word-window').boundingBox();
    assert.ok(dockCurrent.y>=dockWindow.y-1 && dockCurrent.y+dockCurrent.height<=dockWindow.y+dockWindow.height+1,JSON.stringify({dockCurrent,dockWindow}));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:'.test-output/practice-dock-narrow.png'});
    await menuClick('#settings-toggle');
    await page.locator('#dock-font').fill('24');
    await page.locator('#dock-font').dispatchEvent('change');
    await page.locator('#dock-lines').uncheck();
    await menuClick('#settings-toggle');
    assert.ok(Math.abs((await page.locator('#word-window').boundingBox()).height-24*1.85)<1);
    await dockState(10,'g');
    assert.equal(await page.locator('#reading-caret').isVisible(),true);
    await page.screenshot({path:'.test-output/practice-dock-single.png'});
    await menuClick('#settings-toggle');
    assert.equal(await page.locator('#show-dock-caret').isChecked(),true);
    await page.locator('#show-dock-caret').uncheck();
    assert.equal(await page.evaluate(()=>window.messages.filter(m=>m.type==='preferences').at(-1).showDockCaret),false);
    await menuClick('#settings-toggle');
    await dockState(11,'n');
    assert.equal(await page.locator('#reading-caret').isVisible(),false);
    assert.equal(await page.locator('#caret').evaluate(el=>getComputedStyle(el).visibility),'visible');
    await page.screenshot({path:'.test-output/practice-caret-hidden-narrow.png'});
    await page.setViewportSize({width:1200,height:720});
    await page.screenshot({path:'.test-output/practice-caret-hidden-wide.png'});
    await menuClick('#settings-toggle');
    await page.locator('#show-dock-caret').check();
    await menuClick('#settings-toggle');
    assert.equal(await page.locator('#reading-caret').isVisible(),true);
    await page.evaluate(()=>{
      document.body.classList.replace('vscode-dark','vscode-light');
      document.body.style.setProperty('--vscode-editor-background','#ffffff');
      document.body.style.setProperty('--vscode-editor-foreground','#202020');
      document.body.style.setProperty('--vscode-descriptionForeground','#626262');
    });
    await dockState(0,'"He');
    await page.screenshot({path:'.test-output/practice-dock-light.png'});
    await page.evaluate(()=>{
      document.body.classList.replace('vscode-light','vscode-dark');
      document.body.style.setProperty('--vscode-editor-background','#1e1e1e');
      document.body.style.setProperty('--vscode-editor-foreground','#d4d4d4');
      document.body.style.removeProperty('--vscode-descriptionForeground');
    });
    await menuClick('#settings-toggle');
    await page.locator('#dock-style').selectOption('compact');
    await page.locator('#show-progress').uncheck();
    await page.locator('#dock-font').fill('13');
    await page.locator('#dock-font').dispatchEvent('change');
    await page.locator('#dock-lines').uncheck();
    await menuClick('#settings-toggle');
    const compactBox=await page.locator('#prompt-panel').boundingBox();
    assert.ok(compactBox.height<32 && Math.abs(compactBox.y+compactBox.height-692)<1,'compact strip stays above the persistent speech status');
    assert.equal(await page.locator('footer').isVisible(),true);
    assert.equal(await page.locator('#dock-progress').isVisible(),false);
    await page.screenshot({path:'.test-output/practice-compact.png'});
    await menuClick('#settings-toggle');
    await page.locator('#hover-only').check();
    await menuClick('#settings-toggle');
    await page.mouse.move(10,100);
    assert.equal(await page.locator('#word-window').evaluate(el=>getComputedStyle(el).opacity),'0');
    await page.screenshot({path:'.test-output/practice-hidden.png'});
    await page.mouse.move(150,compactBox.y+10);
    assert.equal(await page.locator('#word-window').evaluate(el=>getComputedStyle(el).opacity),'1');
    assert.deepEqual(await page.locator('#prompt-panel').boundingBox(),compactBox,'hover reveals text without changing layout');
    await page.locator('#prompt-panel').click();
    assert.ok(await page.locator('#editor').evaluate(el=>document.activeElement===el),'hover area can focus keyboard input');
    await page.setViewportSize({width:430,height:720});
    await page.mouse.move(150,707);
    await page.screenshot({path:'.test-output/practice-compact-narrow.png'});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.setViewportSize({width:1200,height:720});
    await page.evaluate(() => window.postMessage({type:'state',ready:false,backgroundSuspended:true,reason:'官网窗口已最小化，换词刷新已暂停。'}));
    await page.waitForFunction(() => !document.body.classList.contains('armed'));
    const keyCount=await page.evaluate(() => window.messages.filter(m=>m.type==='key').length);
    await page.keyboard.press('x');
    assert.equal(await page.evaluate(() => window.messages.filter(m=>m.type==='key').length),keyCount);
    await page.evaluate(() => window.postMessage({type:'armed'}));
    await page.waitForFunction(() => document.body.classList.contains('armed'));
    await page.keyboard.press('Control+p');
    assert.ok(await page.evaluate(() => window.messages.some(m => m.type === 'pause')));
    await menuClick('#relay-files');
    await menuClick('#relay-clear');
    for (const type of ['relay-files','relay-clear']) assert.ok(await page.evaluate(type=>window.messages.some(m=>m.type===type),type));
    await dockState(0,'"Hex');
    await dockState(1,'s');
    await menuClick('#settings-toggle');
    for (const mode of ['comment','reading','inline','dock']) {
      await page.locator('#display-mode').selectOption(mode);
      const selector=mode==='inline'?'#inline-hint .inline-word:first-child .incorrect':'#word-list [data-index="0"] .incorrect';
      assert.equal(await page.locator(selector).count(),5,`errors remain after switching to ${mode}`);
    }
    await page.locator('#hover-only').uncheck();
    await page.locator('#hide-on-blur').check();
    await page.locator('#dock-position').selectOption('right');
    await page.locator('#dock-width').fill('420');
    await page.locator('#dock-width').dispatchEvent('change');
    await menuClick('#settings-toggle');
    const cornerBox=await page.locator('#prompt-panel').boundingBox();
    assert.ok(cornerBox.width===420 && cornerBox.x>750 && cornerBox.y>652 && cornerBox.y+cornerBox.height<=692,'short strip is confined to the bottom right above the footer');
    await page.screenshot({path:'.test-output/practice-corner.png'});
    await page.evaluate(()=>window.postMessage({type:'view-active',active:false}));
    await page.waitForFunction(()=>document.body.classList.contains('view-inactive'));
    assert.equal(await page.locator('#prompt-panel').isVisible(),false,'switching window or editor hides the short strip');
    await page.evaluate(()=>window.postMessage({type:'view-active',active:true}));
    await page.waitForFunction(()=>!document.body.classList.contains('view-inactive'));
    assert.equal(await page.locator('#prompt-panel').isVisible(),true);
    await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
    assert.equal(await page.locator('#prompt-panel').isVisible(),false);
    await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
    assert.equal(await page.locator('#prompt-panel').isVisible(),true);
    await page.setViewportSize({width:320,height:640});
    const narrowCorner=await page.locator('#prompt-panel').boundingBox();
    assert.ok(narrowCorner.x>=0 && narrowCorner.x+narrowCorner.width<=320);
    await page.screenshot({path:'.test-output/practice-corner-narrow.png'});
    await dockState(0,'"Hello,"');
    await dockState(1,'she');
    assert.equal(await page.locator('#word-list [data-index="0"] .incorrect').count(),0,'backspace correction clears completed error state');
    assert.equal(await page.locator('#word-list [data-index="0"].extra-error').count(),0);
    await page.setViewportSize({width:1200,height:720});
    await menuClick('#settings-toggle');
    assert.equal(await page.locator('#display-mode option[value="corner"]').count(),0,'the separate corner mode is removed');
    for (const position of ['full','center','right']) {
      await page.locator('#dock-position').selectOption(position);
      await page.locator('#dock-style').selectOption('standard');
      await page.locator('#show-progress').check();
      await page.locator('#dock-lines').check();
      await dockState(0,'"He');
      await menuClick('#settings-toggle');
      const panel=await page.locator('#prompt-panel').boundingBox();
      assert.equal(panel.width,420,'all positions use the configured strip width');
      if (position==='full') {
        assert.equal(panel.x,8,'left strip keeps the same edge inset as the right strip');
        assert.equal(await page.locator('#dock-position option[value="full"]').textContent(),'底部左下');
      }
      if (position==='center') assert.ok(Math.abs(panel.x+panel.width/2-600)<1,'center strip is centered');
      if (position==='right') assert.ok(Math.abs(panel.x+panel.width-1192)<1,'right strip is right aligned');
      assert.equal(await page.locator('#dock-progress').isVisible(),true,'all positions share the standard input indicator');
      const rowCount=await page.locator('#word-list .prompt-word').evaluateAll(words=>{
        const viewport=document.getElementById('word-window').getBoundingClientRect();
        return new Set(words.map(el=>el.getBoundingClientRect()).filter(r=>r.top>=viewport.top-1 && r.bottom<=viewport.bottom+1).map(r=>Math.round(r.y))).size;
      });
      assert.equal(rowCount,2,`${position}: two complete rows are actually visible`);
      await page.screenshot({path:`.test-output/practice-${position}-double.png`});
      await page.setViewportSize({width:320,height:640});
      await dockState(1,'s');
      const narrow=await page.locator('#prompt-panel').boundingBox();
      assert.ok(narrow.x>=0 && narrow.x+narrow.width<=320,`${position}: standard double row fits a narrow editor`);
      const current=await page.locator('#word-list .current').boundingBox();
      const viewport=await page.locator('#word-window').boundingBox();
      assert.ok(current.y>=viewport.y-1 && current.y+current.height<=viewport.y+viewport.height+1,'narrow current word stays visible');
      await page.screenshot({path:`.test-output/practice-${position}-double-narrow.png`});
      await page.setViewportSize({width:1200,height:720});
      await menuClick('#settings-toggle');
      await page.locator('#hover-only').check();
      await menuClick('#settings-toggle');
      await page.mouse.move(10,100);
      assert.equal(await page.locator('#word-window').evaluate(el=>getComputedStyle(el).opacity),'0');
      assert.equal(await page.locator('#dock-progress').evaluate(el=>getComputedStyle(el).opacity),'0','hover hides the input indicator too');
      await page.mouse.move(panel.x+panel.width/2,panel.y+15);
      assert.equal(await page.locator('#word-window').evaluate(el=>getComputedStyle(el).opacity),'1');
      await menuClick('#settings-toggle');
      await page.locator('#hover-only').uncheck();
      await page.locator('#dock-lines').uncheck();
      await page.locator('#hide-on-blur').uncheck();
      await menuClick('#settings-toggle');
      assert.ok(Math.abs((await page.locator('#word-window').boundingBox()).height-13*1.85)<1,'single-line toggle works in every position');
      await page.evaluate(()=>window.postMessage({type:'view-active',active:false}));
      await page.waitForFunction(()=>document.body.classList.contains('view-inactive'));
      assert.equal(await page.locator('#prompt-panel').isVisible(),true,'turning off hide on blur works independently');
      await page.evaluate(()=>window.postMessage({type:'view-active',active:true}));
      await menuClick('#settings-toggle');
    }
    for (const mode of ['comment','reading']) {
      await page.locator('#display-mode').selectOption(mode);
      await page.locator('#dock-lines').check();
      await page.locator('#hover-only').check();
      await menuClick('#settings-toggle');
      await page.mouse.move(5,710);
      assert.equal(await page.locator('#word-window').evaluate(el=>getComputedStyle(el).opacity),'0');
      const panel=await page.locator('#prompt-panel').boundingBox();
      await page.mouse.move(panel.x+100,panel.y+25);
      assert.equal(await page.locator('#word-window').evaluate(el=>getComputedStyle(el).opacity),'1');
      await menuClick('#settings-toggle');
    }
    await page.locator('#display-mode').selectOption('dock');
    await page.locator('#hover-only').uncheck();
    await page.locator('#dock-position').selectOption('center');
    await page.locator('#show-progress').uncheck();
    assert.equal(await page.locator('#dock-progress').isVisible(),false);
    assert.equal(await page.locator('#prompt-panel').evaluate(el=>getComputedStyle(el).columnGap),'0px','hiding progress removes its reserved column');
    await page.locator('#dock-style').selectOption('compact');
    await page.locator('#show-progress').check();
    assert.equal(await page.locator('#dock-progress').isVisible(),true,'compact progress can be enabled independently');
    await page.locator('#screen-centered').check();
    await page.evaluate(()=>{
      Object.defineProperty(window.screen,'width',{configurable:true,value:1920});
      Object.defineProperty(window.screen,'availLeft',{configurable:true,value:0});
      window.dispatchEvent(new MouseEvent('mousemove',{clientX:100,screenX:500}));
      window.dispatchEvent(new MouseEvent('mousemove',{clientX:150,screenX:550}));
    });
    let centered=await page.locator('#prompt-panel').boundingBox();
    assert.ok(Math.abs(centered.x+centered.width/2-560)<1,'screen center subtracts the Webview screen offset instead of using editor center');
    await page.evaluate(()=>window.dispatchEvent(new MouseEvent('mousemove',{clientX:200,screenX:625})));
    centered=await page.locator('#prompt-panel').boundingBox();
    assert.ok(Math.abs(centered.x+centered.width/2-(960-325)/1.5)<1,'pointer calibration accounts for editor zoom');
    await page.evaluate(()=>{
      Object.defineProperty(window.screen,'availLeft',{configurable:true,value:-1920});
      window.dispatchEvent(new MouseEvent('mousemove',{clientX:100,screenX:-1400}));
      window.dispatchEvent(new MouseEvent('mousemove',{clientX:150,screenX:-1350}));
    });
    centered=await page.locator('#prompt-panel').boundingBox();
    assert.ok(Math.abs(centered.x+centered.width/2-540)<1,'negative monitor coordinates are supported');
    await page.evaluate(()=>window.dispatchEvent(new MouseEvent('mousemove',{clientX:160,screenX:1000})));
    centered=await page.locator('#prompt-panel').boundingBox();
    assert.ok(centered.x>=0 && centered.x+centered.width<=1200,'screen centering is clamped inside the editor');
    await page.locator('#screen-centered').uncheck();
    centered=await page.locator('#prompt-panel').boundingBox();
    assert.ok(Math.abs(centered.x+centered.width/2-600)<1,'disabling returns to editor centering');
    await menuClick('#settings-toggle');
    await page.screenshot({path:'.test-output/practice-progress-toggle.png'});
    await menuClick('#settings-toggle');
    await page.locator('#mode').selectOption('quote');
    await page.locator('#amount').selectOption('medium');
    await page.locator('#settings-form button[type=submit]').click();
    assert.ok(await page.evaluate(()=>window.messages.some(m=>m.type==='settings' && m.settings.amount==='medium')));
    await page.evaluate(()=>{
      window.postMessage({type:'round-reset'});
      window.postMessage({type:'preferences',displayMode:'dock',dockPosition:'center',dockWidth:480,dockLines:2,dockFont:18,speechEnabled:false});
    });
    const layoutWords=('Hello, punctuation ! ? . ; : ) ( stays together. supercalifragilisticexpialidocious Keep reading without stopping at twelve words. '.repeat(4).trim()).split(' ').map((text,index)=>({text,index}));
    for (const index of [0,11,12,23,24]) {
      await page.evaluate(data=>window.postMessage({type:'state',ready:true,...data}),{wordIndex:index,target:layoutWords[index].text,typed:'',preview:layoutWords});
      await page.waitForFunction(index=>document.querySelector('.current')?.dataset.index===String(index),index);
      assert.equal(await page.locator('.prompt-word').first().getAttribute('data-index'),'0','dock does not repaginate at fixed word counts');
      assert.equal(await page.locator('#word-list br').count(),0,'dock wraps by width without inserted line breaks');
      assert.ok(await page.locator('.prompt-word').evaluateAll(words=>words.every(word=>new Set([...word.children].map(letter=>Math.round(letter.getBoundingClientRect().top))).size===1)),'letters and attached punctuation never split across lines');
    }
    assert.equal(await page.locator('.word-unit').nth(1).textContent(),'punctuation!?.;:)','standalone closing punctuation stays with the preceding word');
    const beforeAppend=await page.locator('.prompt-word.current').boundingBox();
    await page.evaluate(data=>window.postMessage({type:'state',ready:true,...data}),{wordIndex:24,target:layoutWords[24].text,typed:'',preview:[...layoutWords,{index:layoutWords.length,text:'Additional'}]});
    await page.waitForFunction(()=>document.getElementById('word-list').textContent.endsWith('Additional'));
    assert.deepEqual(await page.locator('.prompt-word.current').boundingBox(),beforeAppend,'appending website preview must not scroll the current row');
    await page.screenshot({path:'.test-output/practice-natural-wrap-480.png'});
    for (let index=25;index<65;index++) {
      const previousX=await page.locator(`.prompt-word[data-index="${index}"]`).evaluate(el=>el.getBoundingClientRect().x);
      await page.evaluate(data=>new Promise(resolve=>{
        const received=event=>{if(event.data.type==='state'){window.removeEventListener('message',received);resolve();}};
        window.addEventListener('message',received);window.postMessage({type:'state',ready:true,...data});
      }),{wordIndex:index,target:layoutWords[index].text,typed:'',preview:layoutWords.slice(Math.max(0,index-24),index+36)});
      const currentX=await page.locator('.prompt-word.current').evaluate(el=>el.getBoundingClientRect().x);
      assert.ok(Math.abs(currentX-previousX)<1,'dropping old preview rows must preserve word alignment');
    }
    await require('./speech-ui-cases')(page);
    await page.evaluate(()=>{
      window.postMessage({type:'round-reset'});
      window.postMessage({type:'report',metrics:{wpm:'25',accuracy:'95%',raw:'26',consistency:'13%',characters:'149/2/1/0',time:'01:12',testType:'quote medium english',source:'On Melancholy Hill'},xp:32,level:17,accountStatus:'官网已保存，经验 +32',localStatus:'已自动保存到本地'});
    });
    await page.waitForFunction(()=>document.getElementById('resume').textContent.includes('wpm 25'));
    assert.equal(await page.locator('footer').isVisible(),true,'compact view shows the result status when the test ends');
    assert.equal(await page.locator('#prompt-panel').isVisible(),false,'result and reading strip never overlap');
    assert.equal(await page.locator('#report').isVisible(),false,'automatic result stays compact until opened');
    assert.ok((await page.locator('#resume').textContent()).includes('XP +32 · Lv 17'));
    await page.locator('#resume').click();
    assert.ok(await page.evaluate(()=>window.messages.some(m=>m.type==='result')));
    await page.evaluate(()=>window.postMessage({type:'show-report'}));
    await page.waitForFunction(()=>!document.getElementById('report').hidden);
    await page.screenshot({path:'.test-output/practice-result.png'});
    await menuClick('#next-test');
    await menuClick('#repeat-test');
    await page.locator('#export').click();
    await page.locator('#print').click();
    for(const type of ['next-test','repeat-test','export','print'])assert.ok(await page.evaluate(type=>window.messages.some(m=>m.type===type),type));
    assert.ok((await page.locator('#account-status').textContent()).includes('+32'));
    assert.equal(await page.locator('#result-image').count(),0,'no screenshot controls remain');
    await page.locator('#report-close').click();
    await page.evaluate(()=>window.postMessage({type:'report',metrics:{wpm:'25',accuracy:'95%'},xp:0,level:18,accountStatus:'官网已保存，经验 +0',localStatus:'已自动保存到本地'}));
    await page.waitForFunction(()=>document.getElementById('resume').textContent.includes('XP +0 · Lv 18'));
    assert.equal(await page.locator('#report').isVisible(),false,'late XP or level updates do not reopen the report');
    await page.locator('#editor').focus();
    await page.keyboard.press('Escape');
    assert.ok(await page.evaluate(() => window.messages.some(m => m.type === 'stop')));
    assert.deepEqual(errors, []);
    console.log('PASS: stable word groups, errors, word/page transitions, narrow layout, code scroll, CSP, real keys, results and actions.');
  } finally { await browser.close(); server.close(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
